music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'
urlpatterns = [
	#/music/
	url(r'^$', views.index, name='index'),

	#/music/21--example
	#we use () to treat 21 as one number and not 2 and 1 individually
	# ?P<album_id> is the way by which we save the album id as a variable
	# hence 21 will be saved as album_id
	url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

	#for writing the favorite logic
	url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=3000)

	def __str__(self):#string representation of Album Object
		return self.album_title +' - '+self.artist


#each song will be linked to an album 
class Song(models.Model):
	album = models.ForeignKey(Album, on_delete = models.CASCADE) #whenever we delete
	#the album red for eg. all the songs in dat album will also be deleted
	#album has pk which is primary key dat becms the dforeign key for song
	file_type = models.CharField(max_length=20)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):#string representation of Album Object
		return self.song_title

music/views.py
from django.shortcuts import render
from django.http import Http404
#from django.http import HttpResponse
from django.shortcuts import render , get_object_or_404
from django.template import loader

from .models import Album #only displaying the Albums n not the songs
from .models import Song
# Create your views here.
def index(request):
	all_albums = Album.objects.all() #connects to DB looks at Albums table
	# and gets us all the albums
	#template = loader.get_template('music/index.html')
	#context = {'all_albums':all_albums}
	#return render(request, 'music/index.html', context)
	return render(request, 'music/index.html', {'all_albums':all_albums})
	#we pass the request ,the file path to thar template and the context that
	#is the data/info template needs


	#return HttpResponse(template.render(context, request))
	#now we want to loop through a ll the albums
	#html=''
	#for album in all_albums:
		#url='/music/' + str(album.id) +'/'
		#html += '<a href="' + url + '">' + album.album_title + '</a><br>'

	

	#return HttpResponse(html)


def detail(request, album_id):
	"""try:
		album = Album.objects.get(pk=album_id)
	except Album.DoesNotExist:
		raise Http404("Album does not exist")"""
	"""Django comes with a shortcut code for raising 404 exception
		first we have to import get_object_or_404 from django.shortcuts"""
	album = get_object_or_404(Album, pk=album_id)
		#This satatement will try to get an object from the album class, pk will sepcify what object it will try to get
		#if it cannot get it it will throw us a 404 

	return render(request, 'music/detail.html', {'album': album})
	#return render("<h2>Details for Album id: " + str(album_id) + "</h2>")	

def favorite(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	try:
		selected_song = album.song_set.get(pk=request.POST['song'])
	except (KeyError, Song.DoesNotExist):
		return render(request, 'music/detail.html', {
			'album' : album,
			'error_message' : "You did not select a valid song",
			})
	else:
		selected_song.is_favorite = True
		selected_song.save()
		return render(request, 'music/detail.html', {'album': album})

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Music</title>
</head>
<body>
	<div class = "first">
		<!--<ul id= "bands"></ul>-->
		{% block body %}
		{% endblock %}
    </div>
    <style type="text/css">
		html{
			background: pink;
			min-height: 100vh;
			align-items: center;
			justify-content: center;
			display: flex;
		}
	</style>
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block body %}
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action= "{% url 'music:favorite' album.id %}" method="post">
	{% csrf_token %}
	{% for song in album.song_set.all %}
		<input type="checkbox" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
		<label for="song{{ forloop.counter }}">
			{{ song.song_title }}
			{% if song.is_favorite %}
				<img src="http://i.imgur.com/b9b13Rd.png" />
			{% endif %}
		</label><br>
	{% endfor %}
	<input type="submit" value="Favorite">
</form>
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
	{% if all_albums %}
	    <h2>Here are my Albums</h2>
		<ul>
			{% for album in all_albums %}
			<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title}}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<h3>You don't have any albums</h3>
	{% endif %}
{% endblock %}
<style type="text/css">
	.h2{
		align-items: center;
		justify-content: center;
		display: flex;
		background-color: red;
		}
</style>